from classes.funciones import generate_alldata_joints_fromIFC,transform_boxes_info_for_bom_excel_and_generate

ruta=input(r'Introduce la ruta del archivo IFC: ')

boxes_objects,joints_bom_lines,inferredconnections_bom_lines,modeledconnections_bom_lines=generate_alldata_joints_fromIFC(ruta)
transform_boxes_info_for_bom_excel_and_generate(boxes_objects,joints_bom_lines,inferredconnections_bom_lines,modeledconnections_bom_lines,ruta)